/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BankrollRouteImport } from './routes/bankroll'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetsIndexRouteImport } from './routes/bets/index'
import { Route as BetsNewRouteImport } from './routes/bets/new'
import { Route as BetsBetIdRouteImport } from './routes/bets/$betId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BankrollRoute = BankrollRouteImport.update({
  id: '/bankroll',
  path: '/bankroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsIndexRoute = BetsIndexRouteImport.update({
  id: '/bets/',
  path: '/bets/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsNewRoute = BetsNewRouteImport.update({
  id: '/bets/new',
  path: '/bets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsBetIdRoute = BetsBetIdRouteImport.update({
  id: '/bets/$betId',
  path: '/bets/$betId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/new': typeof BetsNewRoute
  '/bets/': typeof BetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/new': typeof BetsNewRoute
  '/bets': typeof BetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/new': typeof BetsNewRoute
  '/bets/': typeof BetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bankroll'
    | '/login'
    | '/settings'
    | '/bets/$betId'
    | '/bets/new'
    | '/bets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/bankroll'
    | '/login'
    | '/settings'
    | '/bets/$betId'
    | '/bets/new'
    | '/bets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bankroll'
    | '/login'
    | '/settings'
    | '/bets/$betId'
    | '/bets/new'
    | '/bets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BankrollRoute: typeof BankrollRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  BetsBetIdRoute: typeof BetsBetIdRoute
  BetsNewRoute: typeof BetsNewRoute
  BetsIndexRoute: typeof BetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bankroll': {
      id: '/bankroll'
      path: '/bankroll'
      fullPath: '/bankroll'
      preLoaderRoute: typeof BankrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/': {
      id: '/bets/'
      path: '/bets'
      fullPath: '/bets/'
      preLoaderRoute: typeof BetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/new': {
      id: '/bets/new'
      path: '/bets/new'
      fullPath: '/bets/new'
      preLoaderRoute: typeof BetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/$betId': {
      id: '/bets/$betId'
      path: '/bets/$betId'
      fullPath: '/bets/$betId'
      preLoaderRoute: typeof BetsBetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BankrollRoute: BankrollRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  BetsBetIdRoute: BetsBetIdRoute,
  BetsNewRoute: BetsNewRoute,
  BetsIndexRoute: BetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
