/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BankrollRouteImport } from './routes/bankroll'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BetsIndexRouteImport } from './routes/bets/index'
import { Route as BetsNewRouteImport } from './routes/bets/new'
import { Route as BetsBetIdRouteImport } from './routes/bets/$betId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiExtensionMeRouteImport } from './routes/api/extension/me'
import { Route as ApiExtensionSessionLoginRouteImport } from './routes/api/extension/session/login'
import { Route as ApiExtensionSessionExchangeRouteImport } from './routes/api/extension/session/exchange'
import { Route as ApiExtensionBetsDraftRouteImport } from './routes/api/extension/bets/draft'
import { Route as ApiExtensionBetsCreateRouteImport } from './routes/api/extension/bets/create'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BankrollRoute = BankrollRouteImport.update({
  id: '/bankroll',
  path: '/bankroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsIndexRoute = BetsIndexRouteImport.update({
  id: '/bets/',
  path: '/bets/',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsNewRoute = BetsNewRouteImport.update({
  id: '/bets/new',
  path: '/bets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BetsBetIdRoute = BetsBetIdRouteImport.update({
  id: '/bets/$betId',
  path: '/bets/$betId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionMeRoute = ApiExtensionMeRouteImport.update({
  id: '/api/extension/me',
  path: '/api/extension/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionSessionLoginRoute =
  ApiExtensionSessionLoginRouteImport.update({
    id: '/api/extension/session/login',
    path: '/api/extension/session/login',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExtensionSessionExchangeRoute =
  ApiExtensionSessionExchangeRouteImport.update({
    id: '/api/extension/session/exchange',
    path: '/api/extension/session/exchange',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiExtensionBetsDraftRoute = ApiExtensionBetsDraftRouteImport.update({
  id: '/api/extension/bets/draft',
  path: '/api/extension/bets/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionBetsCreateRoute = ApiExtensionBetsCreateRouteImport.update({
  id: '/api/extension/bets/create',
  path: '/api/extension/bets/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/new': typeof BetsNewRoute
  '/bets/': typeof BetsIndexRoute
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/extension/bets/create': typeof ApiExtensionBetsCreateRoute
  '/api/extension/bets/draft': typeof ApiExtensionBetsDraftRoute
  '/api/extension/session/exchange': typeof ApiExtensionSessionExchangeRoute
  '/api/extension/session/login': typeof ApiExtensionSessionLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/new': typeof BetsNewRoute
  '/bets': typeof BetsIndexRoute
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/extension/bets/create': typeof ApiExtensionBetsCreateRoute
  '/api/extension/bets/draft': typeof ApiExtensionBetsDraftRoute
  '/api/extension/session/exchange': typeof ApiExtensionSessionExchangeRoute
  '/api/extension/session/login': typeof ApiExtensionSessionLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bankroll': typeof BankrollRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/bets/$betId': typeof BetsBetIdRoute
  '/bets/new': typeof BetsNewRoute
  '/bets/': typeof BetsIndexRoute
  '/api/extension/me': typeof ApiExtensionMeRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/extension/bets/create': typeof ApiExtensionBetsCreateRoute
  '/api/extension/bets/draft': typeof ApiExtensionBetsDraftRoute
  '/api/extension/session/exchange': typeof ApiExtensionSessionExchangeRoute
  '/api/extension/session/login': typeof ApiExtensionSessionLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bankroll'
    | '/login'
    | '/settings'
    | '/api/health'
    | '/bets/$betId'
    | '/bets/new'
    | '/bets/'
    | '/api/extension/me'
    | '/api/stripe/webhook'
    | '/api/extension/bets/create'
    | '/api/extension/bets/draft'
    | '/api/extension/session/exchange'
    | '/api/extension/session/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/bankroll'
    | '/login'
    | '/settings'
    | '/api/health'
    | '/bets/$betId'
    | '/bets/new'
    | '/bets'
    | '/api/extension/me'
    | '/api/stripe/webhook'
    | '/api/extension/bets/create'
    | '/api/extension/bets/draft'
    | '/api/extension/session/exchange'
    | '/api/extension/session/login'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bankroll'
    | '/login'
    | '/settings'
    | '/api/health'
    | '/bets/$betId'
    | '/bets/new'
    | '/bets/'
    | '/api/extension/me'
    | '/api/stripe/webhook'
    | '/api/extension/bets/create'
    | '/api/extension/bets/draft'
    | '/api/extension/session/exchange'
    | '/api/extension/session/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BankrollRoute: typeof BankrollRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BetsBetIdRoute: typeof BetsBetIdRoute
  BetsNewRoute: typeof BetsNewRoute
  BetsIndexRoute: typeof BetsIndexRoute
  ApiExtensionMeRoute: typeof ApiExtensionMeRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiExtensionBetsCreateRoute: typeof ApiExtensionBetsCreateRoute
  ApiExtensionBetsDraftRoute: typeof ApiExtensionBetsDraftRoute
  ApiExtensionSessionExchangeRoute: typeof ApiExtensionSessionExchangeRoute
  ApiExtensionSessionLoginRoute: typeof ApiExtensionSessionLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bankroll': {
      id: '/bankroll'
      path: '/bankroll'
      fullPath: '/bankroll'
      preLoaderRoute: typeof BankrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/': {
      id: '/bets/'
      path: '/bets'
      fullPath: '/bets/'
      preLoaderRoute: typeof BetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/new': {
      id: '/bets/new'
      path: '/bets/new'
      fullPath: '/bets/new'
      preLoaderRoute: typeof BetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bets/$betId': {
      id: '/bets/$betId'
      path: '/bets/$betId'
      fullPath: '/bets/$betId'
      preLoaderRoute: typeof BetsBetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/me': {
      id: '/api/extension/me'
      path: '/api/extension/me'
      fullPath: '/api/extension/me'
      preLoaderRoute: typeof ApiExtensionMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/session/login': {
      id: '/api/extension/session/login'
      path: '/api/extension/session/login'
      fullPath: '/api/extension/session/login'
      preLoaderRoute: typeof ApiExtensionSessionLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/session/exchange': {
      id: '/api/extension/session/exchange'
      path: '/api/extension/session/exchange'
      fullPath: '/api/extension/session/exchange'
      preLoaderRoute: typeof ApiExtensionSessionExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/bets/draft': {
      id: '/api/extension/bets/draft'
      path: '/api/extension/bets/draft'
      fullPath: '/api/extension/bets/draft'
      preLoaderRoute: typeof ApiExtensionBetsDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/bets/create': {
      id: '/api/extension/bets/create'
      path: '/api/extension/bets/create'
      fullPath: '/api/extension/bets/create'
      preLoaderRoute: typeof ApiExtensionBetsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BankrollRoute: BankrollRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  BetsBetIdRoute: BetsBetIdRoute,
  BetsNewRoute: BetsNewRoute,
  BetsIndexRoute: BetsIndexRoute,
  ApiExtensionMeRoute: ApiExtensionMeRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiExtensionBetsCreateRoute: ApiExtensionBetsCreateRoute,
  ApiExtensionBetsDraftRoute: ApiExtensionBetsDraftRoute,
  ApiExtensionSessionExchangeRoute: ApiExtensionSessionExchangeRoute,
  ApiExtensionSessionLoginRoute: ApiExtensionSessionLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
